spring.application.name=taskManagementSystem

spring.datasource.url=jdbc:mysql://localhost:3306/taskP
spring.datasource.username=root
spring.datasource.password=3306



spring.jackson.serialization.write-dates-as-timestamps=false
spring.main.allow-bean-definition-overriding=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
